# User config
author: "Willy Nolan"
title: "Willy Nolan"
description: "Stylistically inspired by the past, technologically inspired by the future..."
about:
  - "I am a software engineer focused on improving how people interact with and experience technology. This site contains some of the projects I have created while pursuing those goals."
  - "I studied Communication at Portland State University, Journalism at The University of Southern California and Computer Science at Georgia Tech."
keywords: "Willy Nolan, Software Engineering, Interactive Engineering"
email: "willy@willynolan.com"
linkedin: "https://www.linkedin.com/in/willynolan/"
github: "https://github.com/computersarecool"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
